{
 "title": "Анализ продаж",
 "time": { "from": "2021-06-01T21:00:00.000Z", "to": "2021-07-02T20:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "pos_name_var",
    "label": "Магазины",
    "query": "SELECT pos_name\nFROM datamarts.sales_report"
   },
   {
    "name": "category_var",
    "label": "Категория",
    "query": "SELECT DISTINCT category_name FROM datamarts.sales_report"
   },
   { "name": "top_var", "label": "Топ", "query": "лучших : DESC, худших : ASC" },
   {
    "name": "top_calc_var",
    "label": "Расчитать топ",
    "query": "по выручке : revenue, по количеству : quantity"
   }
  ]
 },
 "panels": [
  {
   "title": "Общая выручка",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(revenue), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)\r\n    AND $__timeFilter(recorded_on)"
    }
   ]
  },
  {
   "title": "Общее количество",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(quantity), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)\r\n    AND $__timeFilter(recorded_on)"
    }
   ]
  },
  {
   "title": "Общий средний чек",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(revenue) / SUM(quantity), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)\r\n    AND $__timeFilter(recorded_on)"
    }
   ]
  },
  {
   "title": "Динамика продаж",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    recorded_on,\r\n    $top_calc_var,\r\n    name_short\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    name_short IN (\r\n        SELECT\r\n            name_short\r\n        FROM\r\n            datamarts.sales_report\r\n        WHERE\r\n            pos_name IN ($pos_name_var)\r\n            AND category_name IN ($category_var)\r\n            AND $__timeFilter(recorded_on)\r\n        GROUP BY\r\n            name_short\r\n        ORDER BY\r\n            SUM($top_calc_var) $top_var\r\n        LIMIT 5\r\n    )"
    }
   ]
  },
  {
   "title": "Доля товара",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "(\r\nSELECT\r\n    name_short,\r\n    SUM($top_calc_var) AS sum_field\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)\r\n    AND $__timeFilter(recorded_on)\r\nGROUP BY\r\n    name_short\r\nORDER BY sum_field $top_var\r\nLIMIT 5\r\n)\r\nUNION\r\n(\r\nSELECT\r\n    'другие' AS name_short,\r\n    SUM(sum_field) AS sum_field\r\nFROM (\r\n    SELECT\r\n        name_short,\r\n        SUM($top_calc_var) AS sum_field\r\n    FROM\r\n        datamarts.sales_report\r\n    WHERE\r\n        pos_name IN ($pos_name_var)\r\n        AND category_name IN ($category_var)\r\n        AND $__timeFilter(recorded_on)\r\n    GROUP BY\r\n        name_short\r\n    ORDER BY sum_field $top_var\r\n    OFFSET 5\r\n) as other_products\r\n)"
    }
   ]
  }
 ]
}