{
 "title": "Отчёт продаж",
 "time": { "from": "2021-05-31T21:00:00.000Z", "to": "2021-07-02T20:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "pos_name_var",
    "label": "Магазин",
    "query": "SELECT pos_name\nFROM datamarts.sales_report"
   },
   {
    "name": "category_var",
    "label": "Категория",
    "query": "SELECT DISTINCT category_name FROM datamarts.sales_report"
   }
  ]
 },
 "panels": [
  {
   "title": "Общее количество",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(quantity), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)\r\n    AND $__timeFilter(recorded_on)"
    }
   ]
  },
  {
   "title": "Общая выручка",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(revenue), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)\r\n    AND $__timeFilter(recorded_on)"
    }
   ]
  },
  {
   "title": "Общий средний чек",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(revenue) / SUM(quantity), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)\r\n    AND $__timeFilter(recorded_on)"
    }
   ]
  },
  {
   "title": "Отчёт продаж",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    name_short AS Товар,\r\n    SUM(quantity) AS Количество,\r\n    SUM(quantity) * 100 / (\r\n        SELECT SUM(quantity)\r\n        FROM datamarts.sales_report\r\n        WHERE\r\n            pos_name IN ($pos_name_var)\r\n            AND category_name IN ($category_var)\r\n            AND $__timeFilter(recorded_on)\r\n    ) AS \"Доля от общего количества, %\",\r\n    SUM(revenue) AS Выручка,\r\n    SUM(revenue) * 100 / (\r\n        SELECT SUM(revenue)\r\n        FROM datamarts.sales_report\r\n        WHERE\r\n            pos_name IN ($pos_name_var)\r\n            AND category_name IN ($category_var)\r\n            AND $__timeFilter(recorded_on)\r\n    ) AS \"Доля от общей выручки, %\",\r\n    SUM(revenue) / SUM(quantity) AS \"Средний чек продукта\"\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)\r\n    AND $__timeFilter(recorded_on)\r\nGROUP BY\r\n    name_short"
    }
   ]
  }
 ]
}