{
 "title": "Сравнительный анализ по периодам",
 "time": { "from": "2021-06-19T21:00:00.000Z", "to": "2021-06-25T20:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "pos_name_var",
    "label": "Магазин",
    "query": "SELECT DISTINCT pos_name FROM datamarts.sales_report"
   },
   {
    "name": "category_var",
    "label": "Категория",
    "query": "SELECT DISTINCT category_name FROM datamarts.sales_report"
   },
   {
    "name": "product_var",
    "label": "Товар",
    "query": "SELECT DISTINCT name_short FROM datamarts.sales_report WHERE category_name IN ($category_var)"
   },
   {
    "name": "interval_var",
    "label": "Предыдущий период",
    "query": "7 дней назад : 7 days, 14 дней назад : 14 days, 1 месяц назад : 1 month, 2 месяца назад : 2 months, 3 месяца назад : 3 months, 6 месяцев назад : 6 months, 1 год назад : 1 year, 2 года назад : 2 years, 3 года назад : 3 years"
   },
   {
    "name": "compare_calc_var",
    "label": "Сравнить",
    "query": "по выручке : SUM(revenue), по количеству : SUM(quantity), по среднему чеку : SUM(revenue)/SUM(quantity)"
   }
  ]
 },
 "panels": [
  {
   "title": "Общая выручка за ранний период",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(revenue), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    $__timeFilter(recorded_on + interval '$interval_var')\r\n    AND name_short IN ($product_var)\r\n    AND pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)"
    }
   ]
  },
  {
   "title": "Общее количество за ранний период",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(quantity), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    $__timeFilter(recorded_on + interval '$interval_var')\r\n    AND name_short IN ($product_var)\r\n    AND pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)"
    }
   ]
  },
  {
   "title": "Общий средний чек за ранний период",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(revenue) / SUM(quantity), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    $__timeFilter(recorded_on + interval '$interval_var')\r\n    AND name_short IN ($product_var)\r\n    AND pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)"
    }
   ]
  },
  {
   "title": "Общая выручка за поздний период",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(revenue), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    $__timeFilter(recorded_on)\r\n    AND name_short IN ($product_var)\r\n    AND pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)"
    }
   ]
  },
  {
   "title": "Общее количество за позний период",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(quantity), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    $__timeFilter(recorded_on)\r\n    AND name_short IN ($product_var)\r\n    AND pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)"
    }
   ]
  },
  {
   "title": "Общий средний чек за подний период",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(SUM(revenue) / SUM(quantity), '999 999 999 999 999')\r\nFROM\r\n    datamarts.sales_report\r\nWHERE\r\n    $__timeFilter(recorded_on)\r\n    AND name_short IN ($product_var)\r\n    AND pos_name IN ($pos_name_var)\r\n    AND category_name IN ($category_var)"
    }
   ]
  },
  {
   "title": "Сравнительный анализ по периодам",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    COALESCE(period1.Дата, period2.Дата) AS Дата,\r\n    period1.field_prev AS \"Ранний период\",\r\n    period2.field_now AS \"Поздний период\"\r\nFROM (\r\n    SELECT\r\n    \trecorded_on::DATE || ' / ' || (recorded_on::DATE + interval '$interval_var')::DATE AS Дата,\r\n\t    $compare_calc_var AS field_prev\r\n\tFROM datamarts.sales_report\r\n\tWHERE\r\n\t    $__timeFilter(recorded_on + interval '$interval_var')\r\n        AND name_short IN ($product_var)\r\n        AND pos_name IN ($pos_name_var)\r\n        AND category_name IN ($category_var)\r\n\tGROUP BY\r\n    \trecorded_on::DATE\r\n    ) AS period1 FULL JOIN (\r\n    SELECT\r\n        (recorded_on::DATE - interval '$interval_var')::DATE || ' / ' || recorded_on::DATE AS Дата,\r\n        $compare_calc_var AS field_now\r\n    FROM datamarts.sales_report\r\n    WHERE\r\n        $__timeFilter(recorded_on)\r\n        AND name_short IN ($product_var)\r\n        AND pos_name IN ($pos_name_var)\r\n        AND category_name IN ($category_var)\r\n    GROUP BY\r\n        recorded_on::DATE\r\n    ) AS period2 ON period1.Дата = period2.Дата\r\nORDER BY Дата"
    }
   ]
  }
 ]
}